### ISSUE TITLE
[Swipe to refresh]  swipe will recompose whole content when item has NavController 

### ISSUE THREAD

**Issue by Icyrockton** [google/accompanist#1112] opened 2022-03-29 00:28 UTC
**Description**
 swipe will recompose whole content when item has NavController 

**Steps to reproduce**

create empty compose project
in build.gradle
```groovy
implementation "com.google.accompanist:accompanist-swiperefresh:0.24.3-alpha"
implementation "androidx.navigation:navigation-compose:2.4.1"
```
copy code
```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    Content()
                }
            }
        }
    }
}

@Composable
fun Content() {
    var refreshing by remember {
        mutableStateOf(false)
    }
    val swipeRefreshState = rememberSwipeRefreshState(isRefreshing = refreshing)
    val navController = rememberNavController()
    LaunchedEffect(refreshing) {
        if (refreshing) {
            delay(2000L)
            refreshing = false
        }
    }
    SwipeRefresh(
        swipeRefreshState,
        onRefresh = {
            refreshing = true
        },
        modifier = Modifier.fillMaxSize()
    ) {
        LazyColumn(modifier = Modifier
            .fillMaxSize()
        ) {

            items((1..100).map { "text ${it}" }) {
                Item(it , navController)          /* <<< ---- recompose whole content */
//                Item(it , null)         /* it's fine , no recompose happened */
            }

        }
    }

}

@Composable
fun Item(data: String, navController: NavController?) {

    Log.d(BuildConfig.APPLICATION_ID, "Item: ${data} recompose")
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(80.dp)
            .clickable(enabled = false) { navController?.navigate("route...") } /* bad happened.. */
            .padding(horizontal = 10.dp, vertical = 10.dp)
            .background(Color.Yellow), contentAlignment = Alignment.Center
    )
    {
        Text(text = data)
    }
}
```
after Build , try to trigger refresh. You will see 
```
Item: text 1 recompose
Item: text 2 recompose
Item: text 3 recompose
Item: text 4 recompose
Item: text 5 recompose
Item: text 6 recompose
Item: text 7 recompose
Item: text 8 recompose
Item: text 9 recompose
Item: text 10 recompose
```

using 
```kotlin 
Item(it , null) 
```
no recompose happened

**Expected behavior** 
no recompose happened  when item has navcontroller

**Additional context**

**Comment by bentrengrove** [comment] 2022-03-29 01:58
`(1..100).map { "text ${it}" }` this line probably needs to be remembered. It will recreate all your items on recompose otherwise, which i guess is happening because your navcontroller is at the highest scope and so is causing the recomposition lower.

If you change it to
```
val navController = rememberNavController()
val myItems = remember { (1..100).map { "text ${it}" }) }

...

LazyColumn {
   ...
   items(myItems) { Item(it , navController) }
}
```

does it still happen?

Another thing I would suggest would be to pass in an event handler rather than the nav holder to your item. This will make it more reusable and might also solve your issue.

```
@Composable
fun Item(data: String, onItemClick: ()->Unit)
```

**Comment by Icyrockton** [comment] 2022-03-29 02:26
I've tried it before, and yes, it still happens.  
I think is related to NavController is not `@Stable` , when refresh happened  `compose runtime` think navcontroller maybe changed  , so trigger recompose .

**Comment by bentrengrove** [comment] 2022-03-29 03:05
That does make sense, but if that's the case I don't think there is much we can do about that from SwipeRefresh?

**Comment by Icyrockton** [comment] 2022-03-29 03:33
But that doesn't happen with lazycolum alone , I think SwipeRefresh trigger some size measurement (not sure)?    🤔
the recompose flow is :
          ```SwipeRefresh trigger some size measurement  ->  navcontroller changed -> recompose item``` 
 (please correct me if I'm wrong)

**Comment by bentrengrove** [comment] 2022-03-29 04:12
I think it is probably this line then
`val swipeRefreshState = rememberSwipeRefreshState(isRefreshing = refreshing)`

The read of `refreshing` would cause the composition scope to be invalidated when `refreshing` changes. I'm not sure there is anything we can do about it but I will keep this issue open for now

**Comment by jossiwolf** [comment] 2022-03-29 14:21
I can explore a bit more but `NavController` not being `@Stable` makes sense as an explanation here. @ianhanniballake, what do you think?

That being said, recomposition isn't inherently bad. While we don't want to recompose more often than necessary, as long as the result of the composition stays the same (which it would in this example), we don't need to re-measure or re-draw. But maybe we can do something here anyway, I'd love to hear Ian's thoughts first.

**Comment by bentrengrove** [comment] 2022-03-29 22:42
Closing as it sounds like this is just working as intended from the additional feedback.

**Closed by bentrengrove** 2022-03-29 22:42 UTC
