### ISSUE TITLE
Glide painter recycler crash - No issue with Coil

### ISSUE THREAD

**Issue by Shusshu** [google/accompanist#406] opened 2021-05-12 15:22 UTC
## Describe the bug
Glide Painter crash with a recycled bitmap issue
this line is part of the stacktrace 
https://github.com/google/accompanist/blob/64e2e4639c0719828d10c81fd2d7a84c13c6ddd1/imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt#L229

When using coil instead of glide it all works fine....

## To Reproduce
1. Displaying an image using glide painter (in a new activity)
2. going to another activity and pressing back to see the image from step 1
3. Press back to see the image from step 1
4. -> Crash

## Expected behavior
No crash

## Environment:
 - Accompanist version: 0.9.1

**Comment by chrisbanes** [comment] 2021-05-12 16:10
Duplicate of #398 I assume.

When creating issues for crashes it obviously helps to post the stack trace.

**Closed by chrisbanes** 2021-05-12 16:10 UTC

**Comment by Shusshu** [comment] 2021-05-12 18:28
Yes, I was going to update it with the trace... I was in a hurry.

I searched the other issue but the title said Coil so I didn't look into the details.... Would help to rename the title to Glide instead as it's spot on.

Thanks @chrisbanes

**Comment by chrisbanes** [comment] 2021-05-13 10:13
I've spent roughly 3 hours trying to recreate this and I can't. I've tried different devices, emulators and content. I'm not going to spend any more time on this without a working reproducible sample.

If you're hitting this, I recommend moving to Coil (which I recommend anyway).
