### ISSUE TITLE
ProvideWindowInsets: Wrong bottom inset with keyboard on API level 21 

### ISSUE THREAD

**Issue by gpouzerate** [google/accompanist#405] opened 2021-05-12 08:26 UTC
## Describe the bug

On API level 21, using ProvideWindowInsets, when the keyboard is opened the bottom inset is too high if using both imePadding() and systemBarsPadding().

## To Reproduce

Try this composable:

```
    MainScreenTheme() {
        ProvideWindowInsets {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .imePadding()
                    .systemBarsPadding()
            ) {
                Text(text = "Top Text",  modifier = Modifier.align(Alignment.TopStart), color = MaterialTheme.colors.onBackground)
                TextField(
                    value = "Bottom TextField",
                    onValueChange = {},
                    modifier = Modifier.align(Alignment.BottomCenter)
                )
            }
        }
    }

```
Initially, when running the composable on the API21 device, the TextFied is correctly aligned at the bottom of the screen.
However, when clicking on the TextField, the keyboard gets opened and now there is an extra margin at the bottom between the bottom of the TextField and the top of the Keyboard. This shouldn't be here.
If using only imePadding and not systemBarsPadding, then the bottom margin is gone (good), but then the top inset is gone as well (bad).
We noticed this bug on API21 but could see that it doesn't occur on API30.
 
## Screenshots?

Appearence on API 21:

![API21 keyboard closed](https://user-images.githubusercontent.com/56931031/117943402-61fecc80-b30c-11eb-9cd4-bdf982ef6f72.png)
![API21 keyboard open](https://user-images.githubusercontent.com/56931031/117943409-632ff980-b30c-11eb-99f1-8a35ba0802ef.png)

Appearence on API 30:

![API30 keyboard closed](https://user-images.githubusercontent.com/56931031/117943447-6cb96180-b30c-11eb-89ab-49cc3f2b53ce.png)
![API30 keyboard open](https://user-images.githubusercontent.com/56931031/117943448-6d51f800-b30c-11eb-97dc-b4014468dc11.png)

## Environment:
 - Android OS version: API Level 21 
 - Device: Emulator Nexus 4
 - Accompanist version: accompanist-insets:0.7.1

**Comment by chrisbanes** [comment] 2021-05-12 09:02
We rely on `androidx.core:core` for all of the underlying functionality. Can you trying updating that to the latest version ([`1.6.0-alpha03`](https://maven.google.com/web/index.html?q=core#androidx.core:core:1.6.0-alpha03))?

Closing this as it's not an Accompanist bug.

**Closed by chrisbanes** 2021-05-12 09:03 UTC

**Comment by gpouzerate** [comment] 2021-05-12 09:23
OK. FYI, same problem occurs on androidx.core:core 1.6.0-alpha03.
I will report there

**Comment by chrisbanes** [comment] 2021-05-12 09:54
Thanks for confirming. Please link the issue here and I'll keep an eye on it

**Comment by gpouzerate** [comment] 2021-05-12 10:16
https://issuetracker.google.com/issues/187844384

**Comment by chrisbanes** [comment] 2021-05-13 08:31
Following on the Android bug. This is working as intended as you're setting both the `ime` inset, combined with the `systemBar` inset. It results in a literal simple `plus` of the two insets.

What you actually want is the [`Modifier.navigationBarsWithImePadding()`](https://google.github.io/accompanist/insets/#animated-insets-support), which does basically does `ime.coerceAtLeast(navigationBars)`. 

In the next release we've got a new way to query for these kind of 'computed' insets: `derivedWindowInsetsTypeOf()`. More to come on that soon.

**Comment by chrisbanes** [comment] 2021-05-13 08:32
I'll clean up the docs a bit, because it only talks about `navigationBarsWithImePadding()` in relation to animated insets, but it's not solely for that.

**Comment by gpouzerate** [comment] 2021-05-14 08:23
Thanks for your investigation.
However, I'm not quite sure the solution you mention fixes the problem: By using only `navigationBarsWithImePadding()` then the issue with the extra margin with the keyboard gets fixed, but then you miss the top padding at the top of the app. See in the screenshot attached: The top text is now under the top bar.

![Pixel2 API29 only navigationBarsWithImePadding](https://user-images.githubusercontent.com/56931031/118243146-665aef00-b49e-11eb-8624-bb87fef6d720.png)

**Comment by chrisbanes** [comment] 2021-05-14 08:46
In that case you want:`Modifier.navigationBarsWithImePadding().statusBarsPadding()` to apply the status bar too

**Comment by gpouzerate** [comment] 2021-05-14 08:51
Oh, you're right. That's the correct combination. Thanks for your help!
