### ISSUE TITLE
Incorrect lifecycle events happen for BottomSheet

### ISSUE THREAD

**Issue by WonderCsabo** [google/accompanist#725] opened 2021-09-16 16:58 UTC
First of all, i am not sure if this is a bug in this library, or navigation(-compose). `ModalBottomSheetLayout` works fine without navigation, though.

## Describe the bug
When the bottom sheet is shown, only `ON_START` lifecycle event is reported inside it. Once it is hidden, `ON_RESUME` arrives. At this point, `ON_RESUME` events are reported to the bottom sheet, but only on start to the main screen.

## To Reproduce
I added to a minimal lifecycle event reporting code to the [official sample](https://google.github.io/accompanist/navigation-material/).

```kotlin
                val navController = rememberNavController()
                val bottomSheetNavigator = rememberBottomSheetNavigator()
                navController.navigatorProvider += bottomSheetNavigator
                ModalBottomSheetLayout(bottomSheetNavigator) {
                    NavHost(navController, "home") {
                        composable(route = "home") {
                            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                                Text(
                                    text = "this is home",
                                    modifier = Modifier.clickable {
                                        navController.navigate("sheet")
                                    }
                                )
                            }

                            val observer = remember {
                                LifecycleEventObserver { _, event ->
                                    Timber.i("home lifecycle $event")
                                }
                            }
                            val lifecycle = LocalLifecycleOwner.current.lifecycle
                            DisposableEffect(lifecycle, observer) {
                                lifecycle.addObserver(observer)
                                onDispose { lifecycle.removeObserver(observer) }
                            }
                        }
                        bottomSheet(route = "sheet") {
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(300.dp)
                            ) {
                                Text("This is a cool bottom sheet!")
                            }

                            val observer = remember {
                                LifecycleEventObserver { _, event ->
                                    Timber.i("bottomsheet lifecycle $event")
                                }
                            }
                            val lifecycle = LocalLifecycleOwner.current.lifecycle
                            DisposableEffect(lifecycle, observer) {
                                lifecycle.addObserver(observer)
                                onDispose { lifecycle.removeObserver(observer) }
                            }
                        }
                    }
                }
 ```
                
When we start the app, these are reported:
```
home lifecycle ON_CREATE
home lifecycle ON_START
home lifecycle ON_RESUME
```

When we show the bottom sheet
```
home lifecycle ON_PAUSE
bottomsheet lifecycle ON_CREATE
bottomsheet lifecycle ON_START
```

When we close the bottom sheet
```
bottomsheet lifecycle ON_RESUME
```

After this, when we push the activity into background and bring it back:
```
bottomsheet lifecycle ON_PAUSE
home lifecycle ON_STOP
bottomsheet lifecycle ON_STOP
home lifecycle ON_START
bottomsheet lifecycle ON_START
bottomsheet lifecycle ON_RESUME
```

## Expected behavior
I would expect the bottom sheet reach `ON_RESUME` once it shown. When it is hidden, the main screen should get the `ON_RESUME` events, not the sheet.

## Environment:
 - Android OS version: Android 10.0
 - Device: Emulator, Google Pixel 3
 - Accompanist version: 0.18

**Comment by jossiwolf** [comment] 2021-09-16 17:50
Can you confirm if this issue happens with Accompanist 0.17.0, too?

**Comment by WonderCsabo** [comment] 2021-09-17 07:14
`0.17.0` seem to work well!

```
// app start
home lifecycle ON_CREATE
home lifecycle ON_START
home lifecycle ON_RESUME
// show bottom sheet
home lifecycle ON_PAUSE
bottomsheet lifecycle ON_CREATE
bottomsheet lifecycle ON_START
bottomsheet lifecycle ON_RESUME
// hide bottom sheet
bottomsheet lifecycle ON_PAUSE
bottomsheet lifecycle ON_STOP
bottomsheet lifecycle ON_DESTROY
home lifecycle ON_RESUME
// app backgrounded then foregrounded
home lifecycle ON_PAUSE
home lifecycle ON_STOP
home lifecycle ON_START
home lifecycle ON_RESUME
```

**Comment by jossiwolf** [comment] 2021-09-17 11:15
Thanks for checking! This is a duplicate of #700 which I am currently working on a fix for. Sorry for the inconvenience!

**Closed** 2021-09-30 07:30 UTC
