### ISSUE TITLE
[Navigation Material] bottomSheet() destination does not get updated values

### ISSUE THREAD

**Issue by chriswiesner** [google/accompanist#1099] opened 2022-03-22 10:19 UTC
## Describe the bug

`bottomSheet()`-Destination composable does not get updated data from inheriting composable.

if i use a `composable()` destination it works fine.

## To Reproduce
See gist here.
https://gist.github.com/chriswiesner/6503999979f67f8fcca33c56a961c245

## Expected behavior
`bottomSheet()` composable also gets updated data

## Screenshots?
[!(bug)](https://user-images.githubusercontent.com/4553058/159457691-96ba8880-637c-4b91-a039-20bb6c02818d.mp4)

[!(working fine)](https://user-images.githubusercontent.com/4553058/159457741-399c07f6-0ed2-446c-aae4-ff8b25f4c2b0.mp4)

## Environment:
 - Android OS version: Android 12
 - Device: Emulator
 - Accompanist version: 0.23.1

**Comment by jossiwolf** [comment] 2022-03-28 16:37
Whoo, this one is interesting. I will investigate and get back to you this week!

**Comment by chriswiesner** [comment] 2022-04-06 07:50
Hey @jossiwolf Any update on that?

**Comment by jossiwolf** [comment] 2022-04-06 13:26
Hi, it looks like this is a Navigation and/or Compose Runtime bug. I was able to repro without any Accompanist dependencies and am currently working on finding a minimal repro. I will post the link to the issue to follow along once I filed it!

**Comment by chriswiesner** [comment] 2022-04-06 15:19
Thanks for investigating! (Sadly this might imply that there is no fix in the near future :/ )

**Comment by jossiwolf** [comment] 2022-04-06 18:27
@chriswiesner In the meantime, I would recommend passing the `State` object instead of the value itself. Not as nice, but it works as a workaround:

```kotlin
class MyViewModel: ViewModel() {
    val viewState = mutableStateOf(...)
    ...
}

**Comment by chriswiesner** [comment] 2022-04-08 13:25
while that solved the issue in the sample i still have problems in my production code.
dug a bit and found an issue.

```
RootNav
- rootScreen
- DetailScreen(MyViewModel())
-- detail home
-- bottomSheet
```

i have nested navigation. creating the VM when navigating to the Detailscreen - (not ideal, i know)
if I use a `bottomSheet{}` destination in the detail screen it somehow triggers a recomposition in the root, resulting in two different VM instances (bottom sheet gets a different VM than the Detail screen home)

if I use `composable {}` destination in the detail screen everything works fine.

Example Gist: https://gist.github.com/chriswiesner/ab2c99f78d34406cd3c52a45108de8ee

**Comment by chriswiesner** [comment] 2022-05-09 05:37
@jossiwolf  did you manage to file an issue on google side?

**Comment by okycelt** [comment] 2022-06-12 01:39
Still seems to be an issue in Accompanist 0.24.10-beta

**Comment by chriswiesner** [comment] 2022-08-12 12:40
seems the issue is still not resolved :/

**Comment by jossiwolf** [comment] 2022-09-23 16:22
@jbw0033 Do you mind taking another look at this? It's been a bit and I didn't make good progress with my investigation :)

**Comment by anhanh11001** [comment] 2023-10-20 11:51
+1 on this, any ideas on fix plan on workaround?

**Comment by ianhanniballake** [comment] 2024-03-08 06:56
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

A number of issues were fixed as part of the migration, but if you're still seeing an issue, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) with a sample project that reproduces your issue and the Material team will take a look.

**Closed by ianhanniballake** 2024-03-08 06:56 UTC
Labels: waiting on dependency
