### ISSUE TITLE
[SwipeRefresh] Crash on scroll.

### ISSUE THREAD

**Issue by Intektor** [google/accompanist#435] opened 2021-05-21 21:06 UTC
## Describe the bug
After updating to compose beta 07 and gradle plugin 7.0.0-beta02 the app crashes on my previously working code.
I tried reproducing the bug on an empty project but couldn't get it to work. But I decided to share the crash with you anyway. 

```kotlin 
                NavHost(navController = rememberNavController(), startDestination = "test") {
                    composable("test") {
                        Scaffold {
                            SwipeRefresh(
                                modifier = Modifier.fillMaxSize(),
                                state = rememberSwipeRefreshState(isRefreshing = false),
                                clipIndicatorToPadding = true,
                                onRefresh = { /*TODO*/ }
                            ) {
                                LazyColumn(modifier = Modifier.fillMaxSize()) {
                                    items((0 until 100).map { }.toList()) {
                                        Box(
                                            modifier = Modifier
                                                .fillMaxWidth()
                                                .height(200.dp)
                                        ) {
                                            Text(
                                                text = "test",
                                                modifier = Modifier.align(Alignment.Center)
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
```
As already mention, this code doesn't crash for me on an empty project while it does in my app, even though the structure is the same.
The crash happens when scrolling the LazyColumn.

The stacktrace:
https://pastebin.com/vEJ8MpbK

The only thing I found out while commenting code in and out while trying to find the source, was, that when the SwipeRefresh code was in it's own Composable function, the code would crash, while it wouldn't crash if I moved it directly into the Scaffold code (very weird). I double checked my libraries for updates but coulnd't find any.

**Comment by chrisbanes** [comment] 2021-05-22 08:20
Duplicate of #428

**Closed by chrisbanes** 2021-05-22 08:20 UTC
