### ISSUE TITLE
[Idea] Navigating back from a bottom sheet should animate

### ISSUE THREAD

**Issue by WonderCsabo** [google/accompanist#724] opened 2021-09-16 12:22 UTC
I am not sure if this is a bug or not, i open it as a feature request just to be sure. :)

**Current behaviour:**

Currently when you close a bottom sheet using `navController.popBackStack()`, the bottom sheet immediately disappears. In the code, i see that `snapTo()` is used, and also the sheet is replaced with an empty view.

**Desired behaviour:**

When `navController.popBackStack()` is called, the sheet should disappear with an animation, just like when we call `animateTo()`.

I understand that we could just call `animateTo()` instead of navigation, however that state is not generally available, and should not be used in VM logic anyway.

**Comment by jossiwolf** [comment] 2021-09-16 14:03
`snapTo` is used because of a bug in `ModalBottomSheetLayout` that hadn't been fixed last time I checked - I'll recheck if we can use `animateTo` now :)

**Comment by WonderCsabo** [comment] 2021-09-16 15:41
Thank you! And also thanks for the great library by the way. 🙏

**Comment by WonderCsabo** [comment] 2021-11-19 08:10
@jossiwolf what should we do with this issue? The Github bot is always complaining. :)

**Comment by jossiwolf** [comment] 2021-12-15 11:21
@WonderCsabo Sorry, we reconfigured the bot now :) The fix for this depends on a larger refactoring that I'm still working on, so there is no good quick fix in the meantime. Sorry about that!

**Comment by WonderCsabo** [comment] 2021-12-15 13:23
No worries! Thanks for the update!

**Comment by jossiwolf** [comment] 2022-01-16 18:12
Obviously, the exemption rule doesn't seem to work🙈 This is still dependent on a larger in-progress refactoring and will take a bit to resolve. Just for further explanation: when navigating, the back stack is updated. We listen for back stack changes and update the sheet's content based on that, which causes the anchors to be recalculated. This means that a longer-running animation (triggered by `animateTo`) will be cancelled, aka the sheet will not be hidden, while a quick animation (`snapTo`) will finish. Unfortunately, this is a known issue upstream that is not trivial to fix, so until we get our own implementation in, there is no viable way to fix this issue.

**Comment by leinardi** [comment] 2022-07-13 15:01
Is there a link to the upstream bug that we can subscribe to?

**Comment by alfroid2k** [comment] 2022-08-10 13:10
Are there any updates on this issue? any workaround?

**Comment by jossiwolf** [comment] 2022-09-23 16:00
No workaround for now, unfortunately. The overall upstream issue can be tracked here: https://issuetracker.google.com/issues/167966118

**Comment by Luis-Gangtime** [comment] 2022-09-26 03:51
Thanks @jossiwolf I did have a look at what was going on and came across the anchors issue as well, it is also noticeable if you try to swap / animate content changes within the sheet as it wont calculate the anchors correctly as its height changes. Ive ended up just settling for doing a barebones implementation of a bottom sheet thats not swipeable and just expands and shrinks for its animation instead of offsetting the content.

**Comment by alfroid2k** [comment] 2022-09-26 03:52
Thanks @jossiwolf I did have a look at what was going on and came across the anchors issue as well, it is also noticeable if you try to swap / animate content changes within the sheet as it wont calculate the anchors correctly as its height changes. Ive ended up just settling for doing a barebones implementation of a bottom sheet thats not swipeable and just expands and shrinks for its animation instead of offsetting the content.

**Comment by DFedonnikov** [comment] 2022-12-31 00:12
> No workaround for now, unfortunately. The overall upstream issue can be tracked here: https://issuetracker.google.com/issues/167966118

Looks like it was fixed :)

**Comment by jossiwolf** [comment] 2023-01-12 07:53
v0.28.1 addresses this issue. Please let us know if you can still reproduce it with this version.

**Closed by jossiwolf** 2023-01-12 07:53 UTC
Labels: enhancement, waiting on dependency

**Comment by tapandesai** [comment] 2023-01-18 15:20
@jossiwolf I can't find v0.28.1 in releases
[https://github.com/google/accompanist/releases](url)

**Comment by jossiwolf** [comment] 2023-01-18 17:52
Apologies, the release is v0.29.0-alpha.
