### ISSUE TITLE
[Navigation Material] Disable dismissing a bottom sheet route

### ISSUE THREAD

**Issue by mkano9** [google/accompanist#1512] opened 2023-02-11 05:49 UTC
**Description**
Is there a way to make a certain bottom sheet route not dismissible when tapping on the area outside the sheet?

**Comment by ReenaYouCan** [comment] 2023-02-14 11:02
I'm also looking out for this kind of implementation.

**Comment by Mukhammaddin6567** [comment] 2023-02-14 13:18
I'm also looking out

**Comment by mkano3** [comment] 2023-02-14 17:54
Hi @jossiwolf, does this seem like something you guys can help with?

**Comment by jossiwolf** [comment] 2023-02-17 16:50
This is a duplicate of #730, please follow along. Unfortunately, we are working on other high-priority items at the moment and can not provide an ETA.

**Closed by jossiwolf** 2023-02-17 16:50 UTC
