### ISSUE TITLE
[Navigation Material] BottomSheet Composable crashing on tablet device

### ISSUE THREAD

**Issue by mehul4795** [google/accompanist#1359] opened 2022-09-30 12:44 UTC
**Description**

The `bottomSheet()` composable works as expected on mobile devices, however, crashes on tablet devices on rotation. Please find the error log below.

```kotlin
java.lang.IllegalArgumentException: The initial value must have an associated anchor.
                                                                                                    	at androidx.compose.material.SwipeableState.ensureInit$material_release(Swipeable.kt:138)
                                                                                                    	at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:594)
                                                                                                    	at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:573)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:278)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:273)
                                                                                                    	at androidx.compose.ui.Modifier$Element.foldIn(Modifier.kt:114)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:222)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:273)
                                                                                                    	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:193)
                                                                                                    	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:192)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:675)
                                                                                                    	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:114)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:341)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:326)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2643)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3260)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3203)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:771)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1031)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:125)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:534)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
```

**Steps to reproduce**

Open the BottomSheet in landscape mode on a tablet device and then rotate the device to portrait. The app gets crashed. This crash is happening for all the BottomSheets as per my observation.

**Expected behavior** 

The BottomSheet should remain as it is without crashing the app.

**Additional context**

**Accompanist Version**: 0.26.4-beta
**Device** : Xiaomi 21051182G (Xiaomi Pad 5)
**Android Version**: Android 11

**Comment by jossiwolf** [comment] 2022-10-04 08:51
Thanks! This is a duplicate of #1147:

> We're aware of this issue, it needs to be fixed upstream. Star for updates: https://issuetracker.google.com/issues/178630869

**Closed by jossiwolf** 2022-10-04 08:51 UTC
