### ISSUE TITLE
[Pager] Adjust page size when elements have different height

### ISSUE THREAD

**Issue by dmitry-stakhov** [google/accompanist#577] opened 2021-07-25 09:42 UTC
## Describe the bug
Pager doesn't wrap content if pages have different size (refer video)

## To Reproduce
1. Set different page height
2. Swipe pages
3. Pager height doesn't adjust

## Video

https://user-images.githubusercontent.com/38129679/126894613-027fd9af-0aec-4155-8d91-3fdda8bc40e1.mp4

## Environment:
 - Android OS version: 9
 - Device: arrowsRX
 - Accompanist version: 0.14.0

## Additional context
Looks like problem is here
`val pagerHeight = placeables.maxOf { it.height }.coerceAtLeast(constraints.minHeight)`

**Comment by chrisbanes** [comment] 2021-07-27 17:02
Duplicate of #413

**Closed by chrisbanes** 2021-07-27 17:02 UTC

**Comment by NitroG42** [comment] 2021-07-28 08:05
@chrisbanes The duplicated issue is about using a fixed list of height per tabs, what if we just want the pager to wrap it's height to the current page height ? 
what would be the best way to "do" this case ?
(I understand it's bad UX, but right now we have two pages, one which is very long, and another one which is basically 50dp)
If you have an answer, it might be interesting to add it to the pager documentation too (I think it still some kinda of a common use case when we use tabs + pager)

**Comment by Talha-mir** [comment] 2021-07-28 10:04
I have the same issue. It gives every page the same height as the page with maximum height and even scroll the other pages as you scroll one of the pages as seen in the video. This is with version 0.11.1. 

https://user-images.githubusercontent.com/81289672/127303910-1be48a52-c022-4651-b11d-b9e501fbe055.mp4

**Comment by chrisbanes** [comment] 2021-08-02 07:34
I'm afraid that is the layout logic we have, and I have no plans or desire to make it more complicated than that.

Interpolating between size changes is complicated and can lead to performance issues.
