### ISSUE TITLE
0.17.0 to 0.18.0 bottomsheet regression: bottomsheet expands fully vs peeking, currentDestination reported incorrectly, bottom sheet opens automatically after swiping it down

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#717] opened 2021-09-14 22:15 UTC
## Describe the bug
In 0.17.0 if I opened up a bottom sheet then it would start at it's peeked height, but now when I open it after updating to 0.18.0 then it opens to fill the entire screen. However if I close it, and open it again, then it goes to it's peek height.

Will add more info as I get more time, but I wanted to file the bug since I know there were some changes to 0.18.0 regarding bottomsheets and so maybe this isn't a bug but an intended change?

**Comment by ColtonIdle** [comment] 2021-09-14 22:26
Also, found another regression? Potentially related. When the sheet is dismissed (you hit back to go to the previous destination) then when calling `navController.currentDestination!!.route` it will still equal `"bottom_sheet"` which it should not. It should equal whatever screen is currently visible. This is different behavior from 0.17.0 to 0.18.0.

**Comment by ColtonIdle** [comment] 2021-09-14 22:29
Also, swiping down on the bottom sheet, makes the bottom sheet appear again.

**Comment by ColtonIdle** [comment] 2021-09-14 22:44
Repro code:

```
NavHost(navController, startDestination = "start", Modifier.padding(innerPadding)) {
        bottomSheet(route = "bottom_sheet") { MyBottomSheet(navController) }
...
```

MyBottomSheet 

```
Box(modifier = Modifier.background(Color(0xffffffff))) {
        Column(
            verticalArrangement = Arrangement.Top,
            modifier = Modifier.fillMaxSize().padding(horizontal = 16.dp),
        ) {
            Text(
                "Thing",
                modifier = Modifier.align(Alignment.CenterHorizontally).padding(vertical = 8.dp))
        }
    }
```

invoked via `navController.navigate("bottom_sheet")`

**Comment by ColtonIdle** [comment] 2021-09-14 22:45
Here is a video of how this works in 0.17.0

https://user-images.githubusercontent.com/31751141/133343575-a9e5608d-d1a6-42da-b135-a6b8c21634ee.mp4

Works as expected. A click opens up the bottom sheet. Drag down. It hides. Click again. It shows.

**Comment by ColtonIdle** [comment] 2021-09-14 22:47
In 0.18.0 you can see that it opens up completely (which takes two swipes down to fully close), and then after clicking again, it does open up only halfway (as expected, like in the 0.17.0 video above), but then when I swipe down, it just opens again.

https://user-images.githubusercontent.com/31751141/133343654-de940eeb-46bf-4c80-af7b-7727c24b09fe.mp4

**Comment by jossiwolf** [comment] 2021-09-15 08:24
Thanks for the report! This looks like a duplicate of #700 which I will address soon.

**Closed** 2021-09-30 07:30 UTC
