### ISSUE TITLE
Can't add padding to top of bottomsheet

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#761] opened 2021-10-01 21:52 UTC
## Describe the bug
When using material navigations ModalBottomSheetLayout you can't add padding to just the top of a bottomsheet. When you add padding it pushes all the contents down, which is problematic when you are using a transparent status bar in edge-to-edge mode. There should be a way to ONLY add a padding to bottom sheets and not the entire layout.

@jossiwolf said that this may be a material bug, but I'm posting here just to make sure it's tracked.

**Comment by Gericop** [comment] 2021-10-12 12:49
This is definitely a material bug as there seems to be no way of setting different padding values for the sheet and the content. This greatly affects the transparent navigation bar too as in landscape the sheet is drawn behind it and if you have rounded corners, they are also going to be behind the navbar. A workaround for now seems to be setting the sheet's background color to transparent and applying a surface to the sheet content directly where you can set the padding any way you want it.

**Comment by jossiwolf** [comment] 2021-12-17 09:26
Well, apparently my "Waiting on Dependency" stale-label-exclusion rule didn't work 🙈

**Comment by mohammadnr2817** [comment] 2023-04-06 17:17
> 

I recently encountered this issue and a workaround was setting `Modifier.fillMaxHeight(fraction = 0.9f)` for sheet content, this way isn’t exactly what you wanted(padding) but neither messes with anything like elevations, etc…

**Comment by mortenholmgaard** [comment] 2023-11-21 10:24
Any new on this?

I looked at the code an it could be solved quite easily by exposing a sheetModifier, but the problem is to support that, there is also a minor change in the material library required,

This is the changes required in com.google.accompanist.navigation.material.BottomSheet:
```
public fun ModalBottomSheetLayout(
    bottomSheetNavigator: BottomSheetNavigator,
    modifier: Modifier = Modifier,
    **sheetModifier: Modifier = Modifier,**
    sheetShape: Shape = MaterialTheme.shapes.large,
    sheetElevation: Dp = ModalBottomSheetDefaults.Elevation,
    sheetBackgroundColor: Color = MaterialTheme.colors.surface,
    sheetContentColor: Color = contentColorFor(sheetBackgroundColor),
    scrimColor: Color = ModalBottomSheetDefaults.scrimColor,
    content: @Composable () -> Unit
) {
    ModalBottomSheetLayout(
        sheetState = bottomSheetNavigator.sheetState,
        sheetContent = bottomSheetNavigator.sheetContent,
        modifier = modifier,
        **sheetModifier = sheetModifier,**
        sheetShape = sheetShape,
        sheetElevation = sheetElevation,
        sheetBackgroundColor = sheetBackgroundColor,
        sheetContentColor = sheetContentColor,
        scrimColor = scrimColor,
        content = content
    )
}
```

And the changes required in androidx.compose.material.ModalBottomSheet:
```
fun ModalBottomSheetLayout(
    sheetContent: @Composable ColumnScope.() -> Unit,
    modifier: Modifier = Modifier,
    **sheetModifier: Modifier = Modifier,**
    sheetState: ModalBottomSheetState =
        rememberModalBottomSheetState(Hidden),
    sheetGesturesEnabled: Boolean = true,
    sheetShape: Shape = MaterialTheme.shapes.large,
    sheetElevation: Dp = ModalBottomSheetDefaults.Elevation,
    sheetBackgroundColor: Color = MaterialTheme.colors.surface,
    sheetContentColor: Color = contentColorFor(sheetBackgroundColor),
    scrimColor: Color = ModalBottomSheetDefaults.scrimColor,
    content: @Composable () -> Unit
) {
    // b/278692145 Remove this once deprecated methods without density are removed
    val density = LocalDensity.current
    SideEffect {
        sheetState.density = density
    }
    val scope = rememberCoroutineScope()
    val orientation = Orientation.Vertical
    BoxWithConstraints(modifier) {
        val fullHeight = constraints.maxHeight.toFloat()
        Box(Modifier.fillMaxSize()) {
            content()
            Scrim(
                color = scrimColor,
                onDismiss = {
                    if (sheetState.anchoredDraggableState.confirmValueChange(Hidden)) {
                        scope.launch { sheetState.hide() }
                    }
                },
                visible = sheetState.anchoredDraggableState.targetValue != Hidden
            )
        }
        Surface(
            **sheetModifier**
                .align(Alignment.TopCenter) // We offset from the top so we'll center from there
                .widthIn(max = MaxModalBottomSheetWidth)
                .fillMaxWidth()
....
```
The changes needed are marked with \** as I could not make it bold in a code block.

**Comment by ianhanniballake** [comment] 2024-03-08 07:03
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

A number of issues were fixed as part of the migration, but if you're still seeing an issue, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) with a sample project that reproduces your issue and the Material team will take a look.

**Closed by ianhanniballake** 2024-03-08 07:03 UTC
Labels: waiting on dependency
