### ISSUE TITLE
[Navigation] Black screen animations

### ISSUE THREAD

**Issue by mattiaferigutti** [google/accompanist#1096] opened 2022-03-19 15:26 UTC
**Description**
I have an app that doesn't support dark mode. If the phone is set to dark mode and you try the fade in/out you'll see that most of the time the screen becomes partially black during the transition. When the phone is in light mode the screen becomes partially white during the transition. Is there a way to keep the light mode behavior even though the phone is set to dark mode?

**Steps to reproduce**
Set the device in dark mode. Support only the light mode.

**Comment by jbw0033** [comment] 2022-04-11 16:27
This seems out of scope for Accompanist Navigation Animation which does not have a say in what the fade looks like, but rather something at the higher level.

I would recommend filing this against the [Animation Compose Component](https://issuetracker.google.com/issues?q=status:open%20componentid:1070767) with a same project that reproduces your issue.

**Closed by jbw0033** 2022-04-11 16:27 UTC
