### ISSUE TITLE
[WebView] Inconsistent loadingState

### ISSUE THREAD

**Issue by 4brunu** [google/accompanist#1607] opened 2023-05-07 07:17 UTC
**Description**
The `loadingState` and consequently `isLoading` is not consistent when the webview finishes loading.

If we test with the accompanist sample project basic webview and add some logs to the loading state, sometimes it ends with `Finished`, sometimes it ends with `Loading(progress=1.0)`, therefore sometimes when the webview ends loading the `isLoading` is `false`, and sometimes is `true`.

**Steps to reproduce**

Add some logs to the `loadingState` and `isLoading` and see their values while reloading the webview several times.

Here are some logs examples of multiple reloads.

```
Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.0)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished
Loading(progress=1.0)

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Loading(progress=1.0)

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Loading(progress=1.0)

Initializing
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Loading(progress=1.0)

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Loading(progress=1.0)

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.1)
Loading(progress=0.0)
Finished

Initializing
Loading(progress=0.0)
Finished
```

**Expected behavior** 

When the webview finished loading the `loadingState` should always be `Finished`, and the `isLoading` should always be `false`.

**Additional context**

**Comment by bentrengrove** [comment] 2023-05-11 01:33
Does this happen no matter what the url or is this specific to a certain page?

**Comment by 4brunu** [comment] 2023-05-11 05:48
I noticed this with some local html, then I tested it with google.com and it had the same behavior, so I think the url doesn't matter

**Comment by Doomsdayrs** [comment] 2023-05-25 16:19
I discovered this seems to occur during rotations reliably. 

The initial load of HTML content will change the state to finished, but any rotations and other window re-compositions will instead return `Loading(progress=1.0)`.

I solved this with [this commit](https://gitlab.com/shosetsuorg/shosetsu/-/commit/6c82118625547706c8eb29bbc864f8e2dd08f22b) on Shosetsu.

**Comment by jhainzlschmid** [comment] 2023-07-04 13:16
The issue occured for me on version **0.30.1**. After upgrading to version **0.31.5-beta** I cannot reproduce it anymore

**Comment by 4brunu** [comment] 2023-08-19 20:12
As far as I know this is still and issue

**Comment by Mwhite69** [comment] 2023-08-19 22:33
Not sure if it me your talking to i gi e you acc to my phone data r what

**Comment by 4brunu** [comment] 2023-08-19 23:19
Sorry, I just added a comment so that the bot wouldn't close de issue

**Comment by bentrengrove** [comment] 2023-08-25 05:12
Unfortunately Accompanist WebView has been deprecated and won't be supported going forwards. I am closing this issue. We recommend you fork the implemenation here and customise it to your needs. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)

**Closed by bentrengrove** 2023-08-25 05:12 UTC
