### ISSUE TITLE
[Navigation Material] 

### ISSUE THREAD

**Issue by Merkost** [google/accompanist#1732] opened 2023-12-01 11:25 UTC
**Description**
Is it possible to show the bottomSheet navigator's destination with fully opened bottom sheet?
I expect to find the `skipHalfExpanded: Boolean` parameter here as it is in ModalBottomSheet

**Comment by ianhanniballake** [comment] 2023-12-04 04:48
Duplicate of #657

**Closed by ianhanniballake** 2023-12-04 04:48 UTC
