### ISSUE TITLE
[Bug][SwipeToRefresh] Crash when trying refresh right after composed

### ISSUE THREAD

**Issue by DtechLabs** [google/accompanist#468] opened 2021-06-05 06:56 UTC
## Describe the bug

Crashing when trying to refresh firstly action, but when before scroll content, then all works correctly

`		SwipeRefresh(
			state = refreshState,
			onRefresh = onRefresh,
			indicatorPadding = PaddingValues(top = 24.dp),
			indicator = { state, refreshTrigger ->
				SwipeRefreshIndicator(
					state = state,
					refreshTriggerDistance = refreshTrigger,
					backgroundColor = Color.Transparent,
					contentColor = MaterialTheme.colors.primary,
					elevation = 0.dp
				)
			}
		) {
			LazyColumn(
				modifier = Modifier
					.width(width),
				state = scrollState,
				verticalArrangement = Arrangement.spacedBy(24.dp)
			) {
				stickyHeader {
                                        .....
                                 }
                                item { ... }
                               ......
                        }
`
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.plasmapay.androidapp, PID: 10722
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <this>
        at androidx.compose.ui.input.nestedscroll.NestedScrollModifierKt.nestedScroll(Unknown Source:2)
        at androidx.compose.ui.input.nestedscroll.NestedScrollModifierKt.nestedScroll$default(NestedScrollModifier.kt:317)
        at com.google.accompanist.swiperefresh.SwipeRefreshKt.SwipeRefresh-Fsagccs(SwipeRefresh.kt:260)
        at com.google.accompanist.swiperefresh.SwipeRefreshKt$SwipeRefresh$3.invoke(Unknown Source:27)
        at com.google.accompanist.swiperefresh.SwipeRefreshKt$SwipeRefresh$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:96)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2139)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2402)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2554)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2525)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:555)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:733)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:102)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:443)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:415)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

## To Reproduce
Swipe to refresh right after the screen appeared

## Environment:
 - Android OS version:  [Android 9.0]
 - Device: [Emulator, Google Pixel 2]
 - Accompanist version: [v0.10.0]

**Comment by chrisbanes** [comment] 2021-06-05 07:02
Update to the latest versions of Accompanist and Compose. Duplicate of #428

**Closed by chrisbanes** 2021-06-05 07:02 UTC
