### ISSUE TITLE
ExperimentalPagerAPI for commonMain in Multiplatform apps

### ISSUE THREAD

**Issue by Nikola-Milovic** [google/accompanist#546] opened 2021-07-08 13:50 UTC
My use-case is as follows, I am trying to create some tabs, I have a common-ui module in the shared module of a Multiplatform app. I have an `@Composable expect fun Tabs()`, that is implemented in the Desktop and the Android modules. A lot of pager stuff has to be marked with `@ExperimentalPagerAPI` which isn't available in the commonMain, meaning that you cannot use even the expect/ actual functions.

CommonMain
```
@Composable
expect fun Tabs() 

@Composable
private fun HomeView() {
    Column {
        Tabs() // causes an error because it's not marked with the annotation
```

Android 
```
@ExperimentalPagerApi // this
@Composable
actual fun Tabs() {
    val pagerState = rememberPagerState(pageCount = 2)

```

Any input or solution to this?

**Comment by chrisbanes** [comment] 2021-07-12 10:16
Unfortunately not yet. This requires Pager (and other libraries in Accompanist) to be built as KMP. I have experimented with that in #393, but we're not there yet. Just opened #552 to track KMP support.

Duplicate of #552

**Closed by chrisbanes** 2021-07-12 10:16 UTC
Labels: enhancement
