### ISSUE TITLE
preview is not working with glide

### ISSUE THREAD

**Issue by hatched-MaciejPrzybylski** [google/accompanist#561] opened 2021-07-14 10:12 UTC
## Describe the bug
preview is not working with glide accompanist (0.13.0)

at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:38)   at com.bumptech.glide.Glide.initializeGlide(Glide.java:278)   at com.bumptech.glide.Glide.initializeGlide(Glide.java:266)   at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:210)   at com.bumptech.glide.Glide.get(Glide.java:191)   at com.bumptech.glide.Glide.getRetriever(Glide.java:774)   at com.bumptech.glide.Glide.with(Glide.java:801)   at com.google.accompanist.glide.GlidePainterDefaults.defaultRequestManager(Glide.kt:71)   at com.google.accompanist.glide.GlideKt.rememberGlidePainter(Glide.kt:94)   at xxx.xxx.xxx.xxx.ScanPayAnGoScannedProductKt.ScanPayAnGoScannedProduct(ScanPayAnGoScannedProduct.kt:69)   at xxx.xxx.xxx.xxx.ScanPayAnGoScannedProductKt.PreviewScanPayAnGoScannedProduct(ScanPayAnGoScannedProduct.kt:117)

## To Reproduce
Image(
                painter = rememberGlidePainter(
                    request = cartItem.product.getDefaultImage()?.url,
                    previewPlaceholder = R.drawable.product_not_ava,
                    fadeIn = true,
                ),
                contentDescription = "",
                contentScale = ContentScale.Inside,
                modifier = Modifier.size(48.dp, 48.dp),

                )

## Expected behavior
preview should work

## Environment:
 - Device: [Android studio]
 - Accompanist version: [0.13.0]

**Comment by chrisbanes** [comment] 2021-07-20 12:17
Duplicate of #424

**Closed by chrisbanes** 2021-07-20 12:17 UTC
