### ISSUE TITLE
[navigation-material] Sometimes bottom sheet entry not correctly popped when dismissed by user

### ISSUE THREAD

**Issue by mxalbert1996** [google/accompanist#700] opened 2021-09-07 05:10 UTC
## Describe the bug

Sometimes when the user dismiss the bottom sheet, it pops up again. 

https://user-images.githubusercontent.com/9391933/132286583-4858b9f9-d859-414f-bc3c-8849d2a71e3d.mp4

## To Reproduce

The [official example](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/material/BottomSheetNavSample.kt) is enough to reproduce this.

## Findings

It seems that the first time we navigate to a bottom sheet entry, the [`sheetState.show()`](https://github.com/google/accompanist/blob/dd384f0b419bb5b95b2cda608520d2866bb248c7/navigation-material/src/main/java/com/google/accompanist/navigation/material/SheetContentHost.kt#L96) call is always canceled, but `sheetState.targetValue` is `Hidden`, so [`currentOnSheetShown(backStackEntry)`](https://github.com/google/accompanist/blob/dd384f0b419bb5b95b2cda608520d2866bb248c7/navigation-material/src/main/java/com/google/accompanist/navigation/material/SheetContentHost.kt#L103) which marks the transition completed is not called. However, the bottom sheet does pop up after that, making the internal and external states inconsistent, which eventually results in the behavior described above.

**Comment by jossiwolf** [comment] 2021-09-07 10:07
Thanks for the report! I believe this issue was introduced/resurfaced with #680. The underlying issue is caused by the Swipeable APIs but I'll try to find a workaround next week.

**Comment by TadejZupancic** [comment] 2021-09-11 06:37
If you click outside the bottom sheet to close it, it closes it, but it does not change the destination. The previous destination that it should pop to can still be used, so it looks like it is working fine. I've noticed it because in my app I have a toolbar button that shows only on that destination and also the bottom navigation does not show any item selected after the bottom sheet is closed.

If you close the bottom sheet with a back press, then it works fine.

I've tried it on the sample app and it also stays on the SHEET destination if you click outside the bottom sheet.

**Comment by mxalbert1996** [comment] 2021-09-11 06:52
What's the point of closing the the bottom sheet without changing the destination?
Besides, this is obviously neither the intended behavior of the source code nor the behavior before 0.18.0.

**Comment by TadejZupancic** [comment] 2021-09-11 07:00
That's obviously a bug, I've updated my post as I see that it could be understood differently as I've intended.

**Comment by rubenquadros12** [comment] 2021-09-23 18:00
@jossiwolf  Can you please share the estimated date of fix/release? Thanks in advance!

**Comment by jossiwolf** [comment] 2021-09-24 09:08
@rubenquadros12 Please excuse the delay - I'm working on a fix but I don't have an estimate yet. I'm hoping for it to be released next week. I will update as soon as I make progress on the fix!

**Comment by Pitam-Poudel** [comment] 2021-09-28 14:45
Please @jossiwolf, is it being fixed ?

**Comment by jossiwolf** [comment] 2021-09-28 15:56
@Pitam-Poudel I understand that this is a very frustrating issue - as mentioned above, the fix is in progress :) The issue is a bit tricky as we have to work around issues in the Material's `ModalBottomSheetLayout` APIs that aren't trivial to fix. I will update here as soon as I have news.

**Comment by chrisbanes** [comment] 2021-09-30 07:53
Will be fixed in the next release (probably today)

**Closed** 2021-09-30 07:53 UTC
