### ISSUE TITLE
[Navigation Material] Provide Material3 version

### ISSUE THREAD

**Issue by leinardi** [google/accompanist#1675] opened 2023-07-11 12:11 UTC
I'm creating this ticket to track the progress on this feature request: Providing a Material 3 version of the Navigation Material.

Currently there is a draft of a PR that implements this (#1543) but it has no changes since 2023.03.13.

There was also another ticket (#1549) requesting this feature but, I think it was wrongly closed as duplicate since it was linking the previous PR and not another ticket.

**Comment by leinardi** [comment] 2023-08-26 11:26
>  Remove stale label or comment or this will be closed in 5 days.

**Comment by kataRebuy** [comment] 2023-10-06 12:14
It would also be super nice if the material3 ModalBottomSheet would be supported by the navigation comoponent

**Comment by ianhanniballake** [comment] 2023-10-15 16:35
Duplicate of #1480

**Closed by ianhanniballake** 2023-10-15 16:35 UTC
