### ISSUE TITLE
[Navigation Material] Bottom sheet disappears when navigating up without animation

### ISSUE THREAD

**Issue by gregnuvo** [google/accompanist#1246] opened 2022-07-13 20:55 UTC
**Description**

Current behavior: When my app does a navigateUp or otherwise navigates away when a bottom sheet is showing, the bottom sheet just disappears.
Desired behavior: When the navigation graph pops the bottom sheet or otherwise navigates away, the bottom sheet should do a show a smooth transition. By default it should show the same animation in reverse that it did when it slid into view.

**Comment by Nek-12** [comment] 2022-07-16 06:02
Duplicate of #724

**Comment by ianhanniballake** [comment] 2022-07-18 00:17
Yep, same issue.

**Closed by ianhanniballake** 2022-07-18 00:17 UTC
