### ISSUE TITLE
[Insets] Bottom padding for the navigationBarsPadding modifier doesn't seem right?

### ISSUE THREAD

**Issue by Bradleycorn** [google/accompanist#449] opened 2021-05-27 16:16 UTC
It seems like there is not quite enough padding added when using the `navigationBarsPadding` modifier to add bottom padding for a bottom Navigation?

See the screen shot below where the LazyColumn is scrolled all the way down, and the bottom few pixels of the last item in the list get "cut off".  Note in the items above you can see that each item has a bit of padding between the bottom line of text and it's `Divider`, but I can't scroll the list far enough to see that bit of padding on the last item (or the divider)... 

![image](https://user-images.githubusercontent.com/4521694/119859948-d8dabe80-bee3-11eb-99da-ddd23a38fa63.png)

## To Reproduce
1. Setup a `Scaffold` inside a `ProvideWindowInsets` composable, and add a `BottomNavigation` to the `bottomBar`.
2. Add a `LazyColumn` as the content of the `Scaffold`, and add the `navigationBarsPadding(left = false, right=false)` modifier.
3. Scroll down to to the last item in the column, and the last few pixels of the last item do not scroll into view.

## Expected behavior
Enough padding should be added by the `navigationBarsPadding` to allow ALL of the content to scroll into view.

## Screenshots?
see above.

## Environment:
 - Android OS version: Android 10
 - Device: Emulator, Google Pixel 4 XL
 - Accompanist version: 0.10.0

**Comment by chrisbanes** [comment] 2021-05-27 17:31
Scaffold's `bottomBar` overlays the bar *over* the content, and tells apps the size of that via the `contentPadding` value provided to the content. `navigationBarsPadding()` has no knowledge of that and only contains the value for the system's navigation bar (the 3-button bar in your example).

You likely need to use the padding values provided to the scaffold content:

``` kotlin
Scaffold() { contentPadding ->
    // Apply contentPadding to LazyColumn too
}
```

**Comment by chrisbanes** [comment] 2021-05-27 17:33
Going to close this, as I don't think it's an Accompanist bug. Feel free to provide a reproducing example, but I think the issue is what I said above.

**Closed by chrisbanes** 2021-05-27 17:33 UTC

**Comment by Bradleycorn** [comment] 2021-05-27 18:00
whoops, yes that is exactly correct, as the documentation for `Scaffold` states ... 
RTFM Brad, RTFM ....

Thanks!
