### ISSUE TITLE
[Navigation Material] 

### ISSUE THREAD

**Issue by VahidGarousi** [google/accompanist#1683] opened 2023-07-19 10:05 UTC
I want to use bottom sheet
1- In some of them, I can disable the ability of the user to click outside the dialog.
2- In some others, I can activate it so that it can be closed by clicking on the area outside the dialog.

How do I do this?

```
    val bottomSheetNavigator = rememberBottomSheetNavigator()
    val navController = rememberNavController(bottomSheetNavigator)

 ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
        sheetBackgroundColor = Color.Transparent,
    ) {
Scaffold()} {
// NAvHost() {
navigation() {

composable() {
Screen
}

bottomSheet() {
Bottom Sheet1, i want to dismiss this bottom sheet when i click out side of this bottom sheet
 }


bottomSheet() {
Bottom Sheet2, i don't want to dismiss this bottom sheet when i click out side of this bottom sheet
 }
}
```

**Comment by VahidGarousi** [comment] 2023-08-02 09:40
No answer?

**Comment by VahidGarousi** [comment] 2023-09-17 07:53
comment :)

**Comment by ianhanniballake** [comment] 2023-10-15 16:34
Duplicate of #730, which also covers the cancellation of the dialog when tapping outside of it or using system back.

**Closed by ianhanniballake** 2023-10-15 16:34 UTC
