### ISSUE TITLE
Setting darkIcons with systemUiController.setStatusBarColor does not work as expected.

### ISSUE THREAD

**Issue by mpost** [google/accompanist#382] opened 2021-04-30 10:49 UTC
## Describe the bug
During the app launch period i want to show a statusbar appearance on the empty activty background. This is controlled via the app theme styles. Now i want to switch the statusbar in onCreate to a different appearance but this does not work. Switching the icons from light style to dark style has no effect.

## To Reproduce
With a an android theme that applies the styles: 

```
<item name="android:windowLightStatusBar">true</item>
<item name="android:statusBarColor">@android:color/transparent</item>
```

The call to set the dark icons has no effect: 
```
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    WindowCompat.setDecorFitsSystemWindows(window, false)
    setContent {
      val systemUiController = rememberSystemUiController()
      SideEffect {
        systemUiController.setStatusBarColor(Color.Transparent, darkIcons = false)
      }
    }
  }
```

## Expected behavior
I would expect to have a white activity background with a light (transparent) statusbar (dark icons). Upon finishing the onCreate call i would expect to have a transparant statusbar with a dark theme (light icons).

## Environment:
 - Android OS version: api 30
 - Device: Emulator
 - Accompanist version: 0.8.1

**Comment by chrisbanes** [comment] 2021-05-02 08:01
This is due to https://issuetracker.google.com/issues/180250984. Closing this as it's not related to Accompanist.

**Closed by chrisbanes** 2021-05-02 08:01 UTC

**Comment by mpost** [comment] 2021-05-03 09:02
Thanks for the info. Closing makes sense 👍. Hope to see the underlying issue improved upon soon.

**Comment by bmonjoie** [comment] 2021-09-13 09:18
I'm wondering if this ticket shouldn't be reopened to change the name of the parameter `darkIcons` to `forceDarkIcons` or something similar?
To me, in its current form, it implies that passing it `false` will fallback to light icons but as the issue @chrisbanes linked states, the expected behavior is to use the theme's default. 
Therefore, in order to have the light icons when passing `false`, the theme must have the following:

```
<item name="android:windowLightStatusBar">false</item>
```

Or maybe the documentation should be improved to reflect this?
