### ISSUE TITLE
[Navigation Material] Bottom Sheet Destination Not Showing

### ISSUE THREAD

**Issue by vinipazzini** [google/accompanist#1509] opened 2023-02-08 11:07 UTC
**Description**
The issue is that the Bottom sheet is not being displayed, when trying to open it a second time

**Steps to reproduce**
Steps are:
1. Tap on "Add New" button
2. Tap on the Text field in order to open the softkeyboard
3. Tap on "action_cancel" button
4. Tap on "Add New" button again

**Expected behavior** 
Bottom sheet should be displayed a second time

**Additional context**
Jetpack Compose version: '1.4.0-alpha05'

Android Studio Electric Eel | 2022.1.1 
Build #AI-221.6008.13.2211.9477386, built on January 11, 2023

Kotlin version: '1.8.0'

**Sample to Reproduce**
https://github.com/vinipazzini/BottomSheetDestinationNotShowing

might be related to: https://github.com/google/accompanist/issues/1503

**Comment by jibe-n** [comment] 2023-02-08 11:23
I'm experiencing the same behavior #1499

**Comment by vinipazzini** [comment] 2023-02-08 12:39
investigating further I found that it works using the following combination of dependencies:
accompanist = "0.28.0"
androidx-compose = "1.4.0-alpha02"

while with the ones below it does not work:
accompanist = "0.29.1-alpha"
androidx-compose = "1.4.0-alpha05"

**Comment by leinardi** [comment] 2023-02-10 10:28
This is still happening with the latest compose `1.4.0-alpha06`.

**Comment by jossiwolf** [comment] 2023-02-17 11:41
Thanks for the report! This is a duplicate of #1499, please follow along there.

**Closed by jossiwolf** 2023-02-17 11:41 UTC
