### ISSUE TITLE
[Pager] AnimateScrollToPage doesnt animate when targetPage < currentPage

### ISSUE THREAD

**Issue by zoltish** [google/accompanist#923] opened 2021-12-14 07:22 UTC
**Description**
The forward animation is always smooth, however when animating backwards (even if its just 1 page); it always snaps to the page. 

**Steps to reproduce**
`state.animateScrollToPage(0)` when on page > 0 does the trick.

**Comment by andkulikov** [comment] 2021-12-14 13:10
Duplicate of https://github.com/google/accompanist/issues/923

**Closed by andkulikov** 2021-12-14 13:10 UTC
