### ISSUE TITLE
Disable gesture for expanding the bottomSheet

### ISSUE THREAD

**Issue by chkmls** [google/accompanist#1501] opened 2023-01-29 09:43 UTC
**Description**
We try to use the bottomSheet with LazyColumn.
The problem is when scrolling the list the bottomSheet is expanded, And we need to keep it only half of the screen(something like tiktok comments).
**Steps to reproduce**
Put LazyColumn in bottomSheet .
**Expected behavior** 
bottomSheet  stays half of screen and gesture is only for closing it
**Additional context**
Thanks

**Comment by jossiwolf** [comment] 2023-02-17 16:49
This is a duplicate of #730.

**Closed by jossiwolf** 2023-02-17 16:49 UTC
